apiVersion: v2
name: sirena-tools
description: Webhook middleware — forwards external service alerts to Mattermost channels
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: SDPSN-devops-charts
    version: 3.3.0
    repository: "https://pic.sg.social.gouv.fr/api/v4/projects/94/packages/helm/stable"
